server:
  port: 80

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/twyunchen/spring-config-server
  application:
    name: config-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server/eureka/